version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: snyk
    versions:
    - 1.440.1
    - 1.440.4
    - 1.440.5
    - 1.445.0
    - 1.446.0
    - 1.447.0
    - 1.448.0
    - 1.450.0
    - 1.452.0
    - 1.454.0
    - 1.455.0
    - 1.456.0
    - 1.457.0
    - 1.458.0
    - 1.459.0
    - 1.460.0
    - 1.462.0
    - 1.464.0
    - 1.467.0
    - 1.471.0
    - 1.474.0
    - 1.476.0
    - 1.478.0
    - 1.483.0
    - 1.486.0
    - 1.487.0
    - 1.489.0
    - 1.491.0
    - 1.495.0
    - 1.500.0
    - 1.503.0
    - 1.505.0
    - 1.509.0
    - 1.511.0
    - 1.514.0
    - 1.518.0
    - 1.521.0
    - 1.522.0
    - 1.526.0
    - 1.528.0
    - 1.529.0
    - 1.530.0
    - 1.532.0
    - 1.538.0
    - 1.541.0
    - 1.542.0
    - 1.557.0
    - 1.563.0
    - 1.564.0
    - 1.566.0
    - 1.570.0
  - dependency-name: wdio-image-comparison-service
    versions:
    - 2.1.0
    - 2.2.0
    - 2.2.1
  - dependency-name: mocha
    versions:
    - 8.3.2
  - dependency-name: yargs-parser
    versions:
    - 5.0.1
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.8
  - dependency-name: "@babel/register"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.13.0
    - 7.13.8
  - dependency-name: moment-timezone
    versions:
    - 0.5.32
    - 0.5.33
  - dependency-name: "@wdio/mocha-framework"
    versions:
    - 6.11.0
  - dependency-name: eslint-plugin-standard
    versions:
    - 4.1.0
  - dependency-name: chromedriver
    versions:
    - 87.0.7
  - dependency-name: "@envage/water-abstraction-helpers"
    versions:
    - 4.3.6
  - dependency-name: "@wdio/cli"
    versions:
    - 6.12.1
